# Generated by Django 6.0.6 on 2026-07-01 19:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='company_logos/')),
                ('about', models.TextField(blank=True, null=True)),
                ('official_message', models.TextField(blank=True, help_text='Official message from placement cell', null=True)),
                ('jd_pdf', models.FileField(blank=True, help_text='Job Description PDF', null=True, upload_to='jd_pdfs/')),
                ('hiring_role', models.CharField(blank=True, help_text='e.g. Software Engineer, Data Analyst', max_length=255, null=True)),
                ('eligibility', models.TextField(blank=True, help_text='Eligibility criteria (CGPA, branches, etc.)', null=True)),
                ('apply_link', models.URLField(blank=True, help_text='Official application link', null=True)),
                ('website', models.URLField(blank=True, null=True)),
                ('deadline', models.DateTimeField(help_text='Application deadline')),
                ('recruitment_process', models.TextField(blank=True, help_text='Recruitment process details', null=True)),
                ('is_published', models.BooleanField(default=False)),
                ('views_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'companies',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PlacementDrive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('drive_date', models.DateField()),
                ('test_date', models.DateField(blank=True, help_text='Online test date', null=True)),
                ('interview_date', models.DateField(blank=True, help_text='Interview date', null=True)),
                ('status', models.CharField(choices=[('upcoming', 'Upcoming'), ('ongoing', 'Ongoing'), ('closed', 'Closed')], default='upcoming', max_length=10)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drives', to='companies.company')),
            ],
            options={
                'ordering': ['drive_date'],
            },
        ),
    ]
